language: java
jdk: oraclejdk8

script:
- ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- ./mvnw test -B
- ./mvnw cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
